version: "3.3"

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "/home:/mnt/Users"
    env_file:
      - postgres.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "7080:8080"
    volumes:
      - "./openapis:/mnt/localdev/openapis"
      - "/home:/mnt/Users"
    environment:
      SWAGGER_JSON: /mnt/openapis/swagger.json

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "7090:8080"
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "/home:/mnt/Users"
      - "/home/reuben/Secrets:/mnt/secrets"

volumes:
  dbdata:
  jenkins_data:
